### ISSUE TITLE
ZMAI-90 not logging energy W and kwh

### ISSUE THREAD

**Issue by swolffke** [PaulAnnekov/tuyaha#44]
When syncing the cloud plugin with Domoticz the KWH and Watt devices are not added for ZMAI-90

**Comment by PaulAnnekov** [comment]
Sorry, I don't understand. How is your issue related to this library?

**Comment by dereitz** [comment]
I'm not certain what the original author intended, but what led me to this issue was that I recently bought some BN-Link BNC-60/U133TJ smart plugs and setup the Tuya integration in Home Assistant.  These plugs are capable of monitoring energy usage.  When I look at the switch in Home Assistant, it doesn't appear to be logging the energy usage.  Is that a limitation of Home Assistant or this library -- or both?  Thanks in advance!  Appreciate all your work on this library!

**Comment by dereitz** [comment]
To the OP, it appears there is another integration option for Home Assistant which includes ability to monitor energy/power:
https://github.com/rospogrigio/localtuya

**Comment by PaulAnnekov** [comment]
Original poster gone.

@dereitz please, create a separate issue for your device. Also check https://github.com/PaulAnnekov/tuyaha#how-to-check-whether-the-api-this-library-using-can-control-your-device for data returned by Tuya API before creating.
